### ISSUE TITLE
Please consider an alternative directory structure

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/generator-swiftserver#375]
```
Sources/MyApp/MyApp ==> Sources/MyApp/my-app-server or Sources/MyApp/MyAppServer 
Sources/MyApp/Application ==> Sources/MyApp/MyApp
```

This makes more sense to me, what do you think?

**Comment by tunniclm** [comment]
Hi @gmosx, the current directories used for a project with name `myapp` are:

- `Sources/myapp`
- `Sources/Application`

The generated executable is: `myapp`.

The application code and the entry point are defined in different modules so that tests can written for the application module (Swift / XCTest does not currently allow testing of executable modules). With that in mind, can you clarify your suggestion of what the directories should be called?

Thanks

**Comment by christiancompton** [comment]
Closing - reopen if needed.
