### ISSUE TITLE
Spaces or underscores in project folder name causes KituraNet to fail when building

### ISSUE THREAD

**Issue by lroseblade** [IBM-Swift/generator-swiftserver#396]
This fails when building in Xcode only! (xcodebuild works)

The path is truncated when attempting to locate CHTTPParser module map

`<unknown>:0: error: no such file or directory: 'folder.xcodeproj/GeneratedModuleMap/CHTTPParser/module.modulemap'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
`

Steps to recreate:
- $ mkdir 'Test folder'
- $ cd ./Test\ folder
- $ kitura init
- $ open "Test folder.xcodeproj"
- Change target to executable
- Run |> project

**Comment by tunniclm** [comment]
Ran a bunch of tests with @lroseblade and we discovered that the problem is specific to these circumstances:
* a dependency has a **generated** `.modulemap` file (these are needed in the case where a C/C++ module is compiled as part of the build, as opposed to a module with a hand-written modulemap that refers to a system library.)
* the package name of the project contains a space (ie the `name` property of the `Package` object in the `Package.swift file contains a space)

For example, we were able to recreate the issue by:
* creating a directory named `new test`
* entering the directory and using `swift package init` to generate a simple project
* adding a dependency on `Kitura-Net` or `omr-agentcore` to the` Package.swif`t -- both these packages contain modules with C/C++ source code.
* running `swift package generate-xcodeproj` (this creates `new test.xcodeproj`)
* opening the xcodeproj in XCode
* hitting the play button to compile (this fails with an error related to the modulemap for CHTTPParser for Kitura-Net, or agentcore for omr-agentcore)

However, when we specified just `CCurl` as a dependency the build succeeded. The `CCurl` package contains a hand-written modulemap for a system installed library rather than having C/C++ source code (where the modulemap gets generated during the build) like the failing case.

In the XCode error we can see in the build output the value in an `-fmodule-map-file` option contains an unescaped space in the path to the generated module map. The directory name `new test` is correctly escaped but the name of the xcode project (`new test.xcodeproj`) directory is not.

As mentioned in the description, the failure only occurs when building in XCode. Building with `swift build` or even `xcodebuild` does not show a problem.
